### ISSUE TITLE
Zeppelin sometimes install fails if db2jcc.jar is already in /tmp

### ISSUE THREAD

**Issue by snowch** [IBM-Bluemix/BigInsights-on-Apache-Hadoop#25]
Zeppelin sometimes install fails if db2jcc.jar is already in /tmp

```
            put from: "${projectDir}/../../downloads/db2jcc.jar",
                into: "/tmp/db2jcc.jar"
```

https://github.com/IBM-Bluemix/BigInsights-on-Apache-Hadoop/blob/master/examples/Zeppelin/build.gradle#L202-L203

Maybe we could check if this file already exists before trying to upload it, or we could put the file in a user folder such as `$ZEPPELIN_HOME/libs`?

**Comment by chriscwmoon** [comment]
putting it into $ZEPPELIN_HOME/lib seems like a good solution.

**Comment by pregazzoni** [comment]
Will take on this one and look to use `ZEPPELIN_HOME/libs`

**Comment by snowch** [comment]
Thanks @pregazzoni
